// Sample data for demo/unauthenticated browsing

export const sampleListings = [
  {
    id: 'sample-1',
    title: 'Organic Cotton Onesie Bundle',
    description: 'Set of 5 organic cotton onesies in soft pastels. Worn gently for one season.',
    category: 'baby_clothes' as const,
    size: '6-9M',
    brand: "Burt's Bees Baby",
    condition: 'like_new' as const,
    looking_for: 'Looking for 12-18M winter pieces',
    location: 'Austin, TX',
    image_urls: ['/onesie-bundle.jpg'],
    is_active: true,
    user_id: 'sample-user-1',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Sarah M.', avatar_url: null, location: 'Austin, TX', is_verified: true },
  },
  {
    id: 'sample-2',
    title: 'Wooden Stacking Toy',
    description: 'Beautiful Montessori-style wooden stacking rings. Non-toxic paint, excellent condition.',
    category: 'toys' as const,
    size: '12M+',
    brand: 'Lovevery',
    condition: 'like_new' as const,
    looking_for: 'Open to any educational toys for 2+',
    location: 'Austin, TX',
    image_urls: ['/wooden-toy.jpg'],
    is_active: true,
    user_id: 'sample-user-2',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Emily R.', avatar_url: null, location: 'Austin, TX', is_verified: true },
  },
  {
    id: 'sample-3',
    title: 'Maternity Wrap Dress',
    description: 'Gorgeous navy maternity wrap dress, perfect for work or special occasions. Size M.',
    category: 'maternity_clothes' as const,
    size: 'M',
    brand: 'Hatch',
    condition: 'good' as const,
    looking_for: 'Looking for nursing-friendly tops',
    location: 'Round Rock, TX',
    image_urls: ['/maternity-dress.jpg'],
    is_active: true,
    user_id: 'sample-user-3',
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Jessica L.', avatar_url: null, location: 'Round Rock, TX', is_verified: false },
  },
  {
    id: 'sample-4',
    title: 'Baby Bjorn Bouncer',
    description: 'Mesh fabric bouncer in great condition. Our baby loved it from 0-6 months.',
    category: 'gear' as const,
    size: '0-6M',
    brand: 'Baby Bjorn',
    condition: 'good' as const,
    looking_for: 'High chair or baby gate',
    location: 'Cedar Park, TX',
    image_urls: ['/baby-bouncer.jpg'],
    is_active: true,
    user_id: 'sample-user-4',
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Amanda K.', avatar_url: null, location: 'Cedar Park, TX', is_verified: true },
  },
  {
    id: 'sample-5',
    title: 'Goodnight Moon Board Book Set',
    description: 'Classic bedtime stories collection. 4 board books in excellent condition.',
    category: 'books' as const,
    size: '0-3Y',
    brand: 'Various',
    condition: 'like_new' as const,
    looking_for: 'Any toddler books',
    location: 'Austin, TX',
    image_urls: ['/board-books.jpg'],
    is_active: true,
    user_id: 'sample-user-5',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Rachel T.', avatar_url: null, location: 'Austin, TX', is_verified: true },
  },
  {
    id: 'sample-6',
    title: 'Linen Bloomers Set',
    description: 'Handmade linen bloomers in dusty rose and sage. Size 18-24M. So sweet!',
    category: 'baby_clothes' as const,
    size: '18-24M',
    brand: 'Handmade',
    condition: 'new_with_tags' as const,
    looking_for: 'Any 2T clothes',
    location: 'Dripping Springs, TX',
    image_urls: ['/linen-bloomers.jpg'],
    is_active: true,
    user_id: 'sample-user-6',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { display_name: 'Lauren B.', avatar_url: null, location: 'Dripping Springs, TX', is_verified: false },
  },
];

export const categoryLabels: Record<string, string> = {
  baby_clothes: 'Baby Clothes',
  maternity_clothes: 'Maternity',
  toys: 'Toys',
  books: 'Books',
  gear: 'Gear',
  other: 'Other',
};

export const conditionLabels: Record<string, string> = {
  new_with_tags: 'New with Tags',
  like_new: 'Like New',
  good: 'Good',
  fair: 'Fair',
};

export const categoryEmojis: Record<string, string> = {
  baby_clothes: '\u{1F476}',
  maternity_clothes: '\u{1F930}',
  toys: '\u{1F9F8}',
  books: '\u{1F4DA}',
  gear: '\u{1F37C}',
  other: '\u{1F4E6}',
};
